vaadin:
  urlMapping: "/ui/*"
  pnpm-enabled: true
logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://rc1c-xozc4qfrylgh5gvb.mdb.yandexcloud.net:6432/team-11?targetServerType=master
    username: team-11
    password: HKLGkjha43
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  h2:
    console:
      enabled: true
      path: /db
